services:
  mediamtx:
    image: ghcr.io/saneslark/mediamtx:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediamtx
    restart: unless-stopped
    network_mode: host
    environment:
      MEDIAMTX_CONFIG: /config/mediamtx.yml
      MEDIAMTX_BASE: http://localhost:9996
      DELAY_NS: 4000000000
    volumes:
      - ./mediamtx.yml:/config/mediamtx.yml:ro
      - ./recordings:/data/recordings
      - ./media_cache:/app/proxy/media_cache
